from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(426, 433)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(102, 5, 321, 106))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.Input_Layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.Input_Layout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.Input_Layout.setContentsMargins(5, 5, 5, 5)
        self.Input_Layout.setSpacing(10)
        self.Input_Layout.setObjectName("Input_Layout")
        self.Input_Edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Input_Edit.sizePolicy().hasHeightForWidth())
        self.Input_Edit.setSizePolicy(sizePolicy)
        self.Input_Edit.setMinimumSize(QtCore.QSize(0, 29))
        self.Input_Edit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.Input_Edit.setText("")
        self.Input_Edit.setFrame(True)
        self.Input_Edit.setClearButtonEnabled(False)
        self.Input_Edit.setObjectName("Input_Edit")
        self.Input_Layout.addWidget(self.Input_Edit)
        self.Search_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Search_Button.sizePolicy().hasHeightForWidth())
        self.Search_Button.setSizePolicy(sizePolicy)
        self.Search_Button.setObjectName("Search_Button")
        self.Input_Layout.addWidget(self.Search_Button)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(2, 120, 421, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.Output_Layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.Output_Layout.setContentsMargins(5, 5, 5, 5)
        self.Output_Layout.setSpacing(10)
        self.Output_Layout.setObjectName("Output_Layout")
        self.Spacer = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.Spacer.setFrameShape(QtWidgets.QFrame.HLine)
        self.Spacer.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Spacer.setObjectName("Spacer")
        self.Output_Layout.addWidget(self.Spacer)
        self.Output_Text = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.Output_Text.setReadOnly(True)
        self.Output_Text.setPlainText("")
        self.Output_Text.setObjectName("Output_Text")
        self.Output_Layout.addWidget(self.Output_Text)
        self.Clear_Button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Clear_Button.setObjectName("Clear_Button")
        self.Output_Layout.addWidget(self.Clear_Button)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 5, 111, 106))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.Sprite_Layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.Sprite_Layout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.Sprite_Layout.setContentsMargins(5, 5, 5, 5)
        self.Sprite_Layout.setSpacing(10)
        self.Sprite_Layout.setObjectName("Sprite_Layout")
        self.Sprite_Label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.Sprite_Label.setText("")
        self.Sprite_Label.setObjectName("Sprite_Label")
        self.Sprite_Layout.addWidget(self.Sprite_Label)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pkmn Searcher"))
        self.Input_Edit.setPlaceholderText(_translate("MainWindow", "Enter Pokemon name or ID"))
        self.Search_Button.setText(_translate("MainWindow", "🔍"))
        self.Clear_Button.setText(_translate("MainWindow", "CLEAR"))
